version: '3.3'

services:
        db:
                image: mysql:5.7
                volumes:
                        - wp_data:/home/colton/dbdata
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: DamnDad124!
                        MYSQL_DATABASE: wordpressDB
                        MYSQL_USER: wordpress
                        MYSQL_PASSWORD: DamnDad124!

        wordpress:
                depends_on:
                        - db
                image: wordpress:latest
                ports:
                        - "8000:80"
                restart: always
                environment:
                        WORDPRESS_DB_HOST: db:3306
                        WORDPRESS_DB_USER: root
                        WORDPRESS_DB_PASSWORD: DamnDad124!
                        WORDPRESS_DB_NAME: colton
volumes:
        wp_data: {}

